const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const writerSchema = new Schema({
	name: String
	// id is auto generated by mongodb
});

module.exports = mongoose.model("Writer",writerSchema);